# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# before_script is used to define the command that should be run before all jobs, including deploy jobs, but after the restoration of artifacts. 
# This can be an array or a multi-line string.
cache:
  paths:
    - .cache/pip
    - venv/
    - public # cache folder to keep all branch updates

before_script:
  - apt-get update
  - apt install -y python-minimal
  - apt install -y python-pip
  - python -V               # Print out python version for debugging
  - apt-get install -y rsync
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

#pages is a special job that is used to upload static content to GitLab that can be used to serve your website
#in this case the developer portal
pages:
  script:
  - pip install -r requirements.txt
  - make html SPHINXOPTS="-W --keep-going"
  - ls build/html
  - mkdir .public
  - cp -r build/html/* .public
  - rm -rf public/$CI_COMMIT_REF_NAME
  - mkdir .public/$CI_COMMIT_REF_NAME
  - cp -r build/html/* .public/$CI_COMMIT_REF_NAME
  - mv .public public
  # "tags" is used to select specific Runners from the list of all Runners that are allowed to run this project
  #tags:
  #  - ska
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    expire_in: 5 days

 # only:
 # - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  #  - rsync -av public /srv/public
  # "tags" is used to select specific Runners from the list of all Runners that are allowed to run this project
  #tags:
  #  - ska
  environment:
    name: staging
# only:
# - master

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://ska-telescope.gitlab.io/developer.skatelescope.org/$CI_COMMIT_REF_NAME/
  only:
    - branches
  except:
    - master
