[tool.poetry]
name = "SKA Developer Portal"
version = "0.2.0"
description = "Documentation space for the SKA Developer community"
authors = ["Your Name <you@example.com>"]
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.8"
docutils = "^0.17.1"
imagesize = "^1.2.0"
Jinja2 = "^3.0.1"
MarkupSafe = "^2.0.1"
Pygments = "^2.9.0"
Sphinx = "^4.0.2"
sphinx-autobuild = "^2021.3.14"
sphinxcontrib-websupport = "^1.2.4"
sphinx-copybutton = "^0.3.3"
sphinx-gitstamp = "^0.3.1"
sphinx-notfound-page = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
