[tool.poetry]
name = "SKA Developer Portal"
version = "0.2.0"
description = "Documentation space for the SKA Developer community"
authors = ["Your Name <you@example.com>"]
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.8"
docutils = "^0.14"
imagesize = "^0.7.1"
Jinja2 = "^2.9.6"
MarkupSafe = "^1.0"
Pygments = "^2.2.0"
sphinx-rtd-theme = "^0.2.4"
Sphinx = "^3.5.2"
sphinx-autobuild = "^0.7.1"
sphinxcontrib-websupport = "^1.0.1"
sphinx-copybutton = "^0.3.0"
sphinx-gitstamp = "^0.3.1"
sphinx-notfound-page = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
